<?php
$z[0]=Array("global","",2127,2159);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",2247,2279);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",2367,2399);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",2487,2519);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",2607,2639);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",2727,2759);
$z[5][4]['name']="cfg_templets_skin";

?>