<?php
$z[0]=Array("global","",2420,2452);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",2547,2579);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",2674,2706);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",2801,2833);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",2928,2960);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",3055,3087);
$z[5][4]['name']="cfg_templets_skin";

?>