<?php
$z[0]=Array("global","",140,165);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",302,327);
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("channel","\r\n                <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n                ",363,599);
$z[2][4]['type']="top";
$z[2][4]['row']="10";
$z[2][4]['currentstyle']="<li class='active'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";

?>